# Generated by Django 3.2.12 on 2023-05-03 06:12

from django.db import migrations, models
from django.db.migrations.operations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ('pgpubsub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        RunSQL(
            "ALTER TABLE pgpubsub_notification ALTER COLUMN created_at SET DEFAULT now()",
        ),
    ]
