# Generated by Django 3.2.12 on 2023-05-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20230411_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='size',
            field=models.BigIntegerField(default=10000),
            preserve_default=False,
        ),
    ]
